### ISSUE TITLE
Links open new tabs on Chrome

### ISSUE THREAD

**Issue by chadlupkes** [sovenor/bitcoin-rocks#1]
My first suggestion is that you change the links so that they don't open new tabs every time something is clicked.  As long as a link is internal, pointing to a page on the same server (bitcoin.rocks), there is no need to open a new tab every time.

**Comment by chadlupkes** [comment]
The reason this is happening is because you have included {target="_blank"} within every link.  Removing those would make the link open the new page within the same tab.

**Comment by sovenor** [comment]
Thanks for the suggestion! I will make this change to internal links.
