### ISSUE TITLE
Translated result messages are not being displayed in the Compound Inflation Calculator

### ISSUE THREAD

**Issue by sfr0xyz** [sovenor/bitcoin-rocks#16]
I've noticed that the result message when calculating the compound inflation is not properly displaying the translated strings.

- On the 'compound-inflation-calculator' page the result is not translated at all ![bitcoin-rocks_cic](https://github.com/sovenor/bitcoin-rocks/assets/144374924/8e5ddb7e-7aae-4f0c-8e3c-305730f6cb87)
- On the 'inflation' page the result is only partially translated 
![bitcoin-rocks_inflation](https://github.com/sovenor/bitcoin-rocks/assets/144374924/095a0ba9-f31b-4ab0-b37c-b111d8e5c332)

It would also be nice to be able to select the salary currency, or in the case of the 'inflation' page, using the currency already selected.

**Comment by sovenor** [comment]
Good catch! I will fix this next week at the latest. That's a great idea to let people select the currency / use the currency already selected on the inflation page. I will implement that too.

**Comment by sovenor** [comment]
Just following up to say I have not forgotten about this. I just didn't have the time I expected to have. This is on my short list of things to do next.

**Comment by sfr0xyz** [comment]
Thank you, it looks very good!

As I was testing it, I realised that there are two plural forms of years in German, which I hadn't considered when translating. It would be 'Jahre', which is correct for the years input field, and 'Jahren', which would be the correct form for the result message.
I'm not sure if this applies to German only, or to other languages as well. It would require two 'years' translation strings in the `common.json`, which might be a bit confusing in other languages.

Another nice feature to consider would be to format the number in the language-specific formats (<https://en.wikipedia.org/wiki/Decimal_separator#Examples_of_use>). Should I open a new issue or work on a PR for it?

**Comment by sovenor** [comment]
If you could work on a PR for it that would be great!

Please note the calculators on the /inflation.html page use jquery/compound-inflation-calculator.js and the standalone calculator on /compound-inflation-calculator.html uses jquery/compound-inflation-calculator-solo.js

Both files are similar but jquery/compound-inflation-calculator.js uses slightly different code to allow for multiple calculators on the same page. Let me know if you have any questions as you are working @sfr0xyz.

**Comment by sfr0xyz** [comment]
> If you could work on a PR for it that would be great!

I'll be working on it in the next few days.

> Please note the calculators on the /inflation.html page use jquery/compound-inflation-calculator.js and the standalone calculator on /compound-inflation-calculator.html uses jquery/compound-inflation-calculator-solo.js
>
> Both files are similar but jquery/compound-inflation-calculator.js uses slightly different code to allow for multiple calculators on the same page. Let me know if you have any questions as you are working @sfr0xyz.

Thanks for the notes! I'll come back to you if I have any further questions.
